version: "3.9"

services:
  checkout-service-api-docs:
    image: redocly/redoc
    volumes:
      - ./services/checkout-service/docs/api:/usr/share/nginx/html/api
    ports:
      - "8080:80"
    environment:
      PAGE_TITLE: "Checkout Service API"
      SPEC_URL: api/specification.yml
  shipping-service-api-docs:
    image: redocly/redoc
    volumes:
      - ./services/shipping-service/docs/api:/usr/share/nginx/html/api
    ports:
      - "8081:80"
    environment:
      PAGE_TITLE: "Shipping Service API"
      SPEC_URL: api/specification.yml
  payments-service-api-docs:
    image: redocly/redoc
    volumes:
      - ./services/payments-service/docs/api:/usr/share/nginx/html/api
    ports:
      - "8082:80"
    environment:
      PAGE_TITLE: "Payments Service API"
      SPEC_URL: api/specification.yml
