version: "3.9"

services:
  doc:
    image: redocly/redoc
    volumes:
      - ./:/usr/share/nginx/html/api
    ports:
      - 8080:80
    environment:
      PAGE_TITLE: "Checkout Service API"
      SPEC_URL: api/specification.yml
